-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 16:24:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`doctor` ;

CREATE TABLE IF NOT EXISTS `hospital`.`doctor` (
  `doctorid` INT NOT NULL AUTO_INCREMENT,
  `personalnumber` VARCHAR(14) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `position` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`doctorid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`nurse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`nurse` ;

CREATE TABLE IF NOT EXISTS `hospital`.`nurse` (
  `nurseid` INT NOT NULL AUTO_INCREMENT,
  `personalnumber` VARCHAR(14) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `position` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`nurseid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`patient` ;

CREATE TABLE IF NOT EXISTS `hospital`.`patient` (
  `personalnumber` VARCHAR(14) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`personalnumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`department` ;

CREATE TABLE IF NOT EXISTS `hospital`.`department` (
  `departmentid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `head` INT NULL,
  PRIMARY KEY (`departmentid`),
  INDEX `head_idx` (`head` ASC) VISIBLE,
  CONSTRAINT `head_department`
    FOREIGN KEY (`head`)
    REFERENCES `hospital`.`doctor` (`doctorid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`affiliation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`affiliation` ;

CREATE TABLE IF NOT EXISTS `hospital`.`affiliation` (
  `doctor` INT NOT NULL,
  `department` INT NOT NULL,
  `isaffiliationprimary` TINYINT NOT NULL,
  PRIMARY KEY (`doctor`, `department`),
  INDEX `department_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `doctor_affiliation`
    FOREIGN KEY (`doctor`)
    REFERENCES `hospital`.`doctor` (`doctorid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `department_affiliation`
    FOREIGN KEY (`department`)
    REFERENCES `hospital`.`department` (`departmentid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`procedure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`procedure` ;

CREATE TABLE IF NOT EXISTS `hospital`.`procedure` (
  `procedureid` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`procedureid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`certification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`certification` ;

CREATE TABLE IF NOT EXISTS `hospital`.`certification` (
  `doctor` INT NOT NULL,
  `procedure` INT NOT NULL,
  `date_certificationstart` DATE NOT NULL,
  `date_certificationend` DATE NOT NULL,
  PRIMARY KEY (`doctor`, `procedure`),
  INDEX `procedure_idx` (`procedure` ASC) VISIBLE,
  CONSTRAINT `doctor_certification`
    FOREIGN KEY (`doctor`)
    REFERENCES `hospital`.`doctor` (`doctorid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `procedure_certification`
    FOREIGN KEY (`procedure`)
    REFERENCES `hospital`.`procedure` (`procedureid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`medication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`medication` ;

CREATE TABLE IF NOT EXISTS `hospital`.`medication` (
  `medicationid` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `brand` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`medicationid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`appointment` ;

CREATE TABLE IF NOT EXISTS `hospital`.`appointment` (
  `appointmentid` INT NOT NULL AUTO_INCREMENT,
  `patient` VARCHAR(14) NOT NULL,
  `doctor` INT NOT NULL,
  `nurse` INT NOT NULL,
  `dt_time_start` DATETIME NOT NULL,
  `dt_time_end` DATETIME NOT NULL,
  `examinationroom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`appointmentid`),
  INDEX `patient_idx` (`patient` ASC) VISIBLE,
  INDEX `nurse_idx` (`nurse` ASC) VISIBLE,
  INDEX `doctor_idx` (`doctor` ASC) VISIBLE,
  CONSTRAINT `patient_appointment`
    FOREIGN KEY (`patient`)
    REFERENCES `hospital`.`patient` (`personalnumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `doctor_appointment`
    FOREIGN KEY (`doctor`)
    REFERENCES `hospital`.`doctor` (`doctorid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `nurse_appointment`
    FOREIGN KEY (`nurse`)
    REFERENCES `hospital`.`nurse` (`nurseid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`diagnosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`diagnosis` ;

CREATE TABLE IF NOT EXISTS `hospital`.`diagnosis` (
  `diagnosisid` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`diagnosisid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`patient_diagnosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`patient_diagnosis` ;

CREATE TABLE IF NOT EXISTS `hospital`.`patient_diagnosis` (
  `patient` VARCHAR(14) NOT NULL,
  `diagnosis` INT NOT NULL,
  `date_diagnosed` DATE NOT NULL,
  PRIMARY KEY (`patient`, `diagnosis`),
  INDEX `diagnosis_idx` (`diagnosis` ASC) VISIBLE,
  CONSTRAINT `patient_patient_diagnosis`
    FOREIGN KEY (`patient`)
    REFERENCES `hospital`.`patient` (`personalnumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `diagnosis_patient_diagnosis`
    FOREIGN KEY (`diagnosis`)
    REFERENCES `hospital`.`diagnosis` (`diagnosisid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`allergy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`allergy` ;

CREATE TABLE IF NOT EXISTS `hospital`.`allergy` (
  `allergyid` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`allergyid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`patient_allergy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`patient_allergy` ;

CREATE TABLE IF NOT EXISTS `hospital`.`patient_allergy` (
  `patient` VARCHAR(14) NOT NULL,
  `allergy` INT NOT NULL,
  `date_diagnosed` DATE NOT NULL,
  PRIMARY KEY (`patient`, `allergy`),
  INDEX `allergy_idx` (`allergy` ASC) VISIBLE,
  CONSTRAINT `patient_patient_allergy`
    FOREIGN KEY (`patient`)
    REFERENCES `hospital`.`patient` (`personalnumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `allergy_patient_allergy`
    FOREIGN KEY (`allergy`)
    REFERENCES `hospital`.`allergy` (`allergyid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`prescription` ;

CREATE TABLE IF NOT EXISTS `hospital`.`prescription` (
  `doctor` INT NOT NULL,
  `patient` VARCHAR(14) NOT NULL,
  `medication` INT NOT NULL,
  `date` DATE NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`doctor`, `patient`, `medication`),
  INDEX `patient_idx` (`patient` ASC) VISIBLE,
  INDEX `medication_idx` (`medication` ASC) VISIBLE,
  CONSTRAINT `doctor_prescription`
    FOREIGN KEY (`doctor`)
    REFERENCES `hospital`.`doctor` (`doctorid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `patient_prescription`
    FOREIGN KEY (`patient`)
    REFERENCES `hospital`.`patient` (`personalnumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `medication_prescription`
    FOREIGN KEY (`medication`)
    REFERENCES `hospital`.`medication` (`medicationid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`block` ;

CREATE TABLE IF NOT EXISTS `hospital`.`block` (
  `blockid` INT NOT NULL AUTO_INCREMENT,
  `blockletter` CHAR NOT NULL,
  `floor` TINYINT NOT NULL,
  PRIMARY KEY (`blockid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`room` ;

CREATE TABLE IF NOT EXISTS `hospital`.`room` (
  `roomnumber` INT NOT NULL,
  `roomtype` VARCHAR(45) NOT NULL,
  `block` INT NOT NULL,
  `isavailable` TINYINT NOT NULL,
  PRIMARY KEY (`roomnumber`),
  INDEX `block_idx` (`block` ASC) VISIBLE,
  CONSTRAINT `block_room`
    FOREIGN KEY (`block`)
    REFERENCES `hospital`.`block` (`blockid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`hospitalization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`hospitalization` ;

CREATE TABLE IF NOT EXISTS `hospital`.`hospitalization` (
  `hospitalizationid` INT NOT NULL AUTO_INCREMENT,
  `patient` VARCHAR(14) NOT NULL,
  `room` INT NULL,
  `dt_time_start` DATETIME NOT NULL,
  `dt_time_end` DATETIME NOT NULL,
  PRIMARY KEY (`hospitalizationid`),
  INDEX `patient_idx` (`patient` ASC) VISIBLE,
  INDEX `room_idx` (`room` ASC) VISIBLE,
  CONSTRAINT `patient_hospitalization`
    FOREIGN KEY (`patient`)
    REFERENCES `hospital`.`patient` (`personalnumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `room_hospitalization`
    FOREIGN KEY (`room`)
    REFERENCES `hospital`.`room` (`roomnumber`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`treatment` ;

CREATE TABLE IF NOT EXISTS `hospital`.`treatment` (
  `patient` VARCHAR(14) NOT NULL,
  `doctor` INT NULL,
  `nurse` INT NULL,
  `procedure` INT NOT NULL,
  `hospitalization` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`patient`, `procedure`, `hospitalization`, `date`),
  INDEX `doctor_idx` (`doctor` ASC) VISIBLE,
  INDEX `nurse_idx` (`nurse` ASC) VISIBLE,
  INDEX `procedure_idx` (`procedure` ASC) VISIBLE,
  INDEX `hospitalization_idx` (`hospitalization` ASC) VISIBLE,
  CONSTRAINT `patient_treatment`
    FOREIGN KEY (`patient`)
    REFERENCES `hospital`.`patient` (`personalnumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `doctor_treatment`
    FOREIGN KEY (`doctor`)
    REFERENCES `hospital`.`doctor` (`doctorid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `nurse_treatment`
    FOREIGN KEY (`nurse`)
    REFERENCES `hospital`.`nurse` (`nurseid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `procedure_treatment`
    FOREIGN KEY (`procedure`)
    REFERENCES `hospital`.`procedure` (`procedureid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hospitalization_treatment`
    FOREIGN KEY (`hospitalization`)
    REFERENCES `hospital`.`hospitalization` (`hospitalizationid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`bill` ;

CREATE TABLE IF NOT EXISTS `hospital`.`bill` (
  `billid` INT NOT NULL AUTO_INCREMENT,
  `patient` VARCHAR(14) NOT NULL,
  `date_issued` DATE NOT NULL,
  `total_cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`billid`),
  INDEX `fk_bill_1_idx` (`patient` ASC) VISIBLE,
  CONSTRAINT `patient_bill`
    FOREIGN KEY (`patient`)
    REFERENCES `hospital`.`patient` (`personalnumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`payment` ;

CREATE TABLE IF NOT EXISTS `hospital`.`payment` (
  `paymentid` INT NOT NULL AUTO_INCREMENT,
  `bill` INT NOT NULL,
  `date_paid` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`paymentid`),
  INDEX `bill_idx` (`bill` ASC) VISIBLE,
  CONSTRAINT `bill_payment`
    FOREIGN KEY (`bill`)
    REFERENCES `hospital`.`bill` (`billid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`duty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`duty` ;

CREATE TABLE IF NOT EXISTS `hospital`.`duty` (
  `nurse` INT NOT NULL,
  `block` INT NOT NULL,
  `dt_time_start` DATETIME NOT NULL,
  `dt_time_end` DATETIME NOT NULL,
  PRIMARY KEY (`nurse`, `block`, `dt_time_start`, `dt_time_end`),
  INDEX `block_idx` (`block` ASC) VISIBLE,
  CONSTRAINT `nurse_duty`
    FOREIGN KEY (`nurse`)
    REFERENCES `hospital`.`nurse` (`nurseid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `block_duty`
    FOREIGN KEY (`block`)
    REFERENCES `hospital`.`block` (`blockid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

DELIMITER $$
CREATE TRIGGER check_room_availability
BEFORE INSERT ON hospitalization
FOR EACH ROW
BEGIN
    DECLARE room_availability BOOLEAN;
    SELECT isavailable INTO room_availability FROM room WHERE roomnumber = NEW.room;
    IF room_availability = FALSE THEN 
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error: Room is not available';
    END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER update_certification_end_date
AFTER UPDATE ON `procedure`
FOR EACH ROW
BEGIN
    UPDATE certification
    SET date_certificationend = NOW()
    WHERE `procedure` = NEW.procedureid;
END$$
DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
